services:
  dev-db:
    image: postgres:15
    container_name: dev-db
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5434:5432"
    networks:
      - lsib-network
    volumes:
      - ./db-data-dev:/var/lib/postgresql/data
  test-db:
    image: postgres:15
    container_name: test-db
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5435:5432"
    networks:
      - lsib-network
    volumes:
      - ./db-data-test:/var/lib/postgresql/data
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@email.com
      PGADMIN_DEFAULT_PASSWORD: adminpass
    ports:
      - "8080:80"
    volumes:
      - ./pgadmin4/server.json:/pgadmin4/servers.json
networks:
  lsib-network: