services:
  dev-db:
    image: postgres:15
    container_name: dev-db
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5434:5432"
    networks:
      - lsib-network
    volumes:
      - ./db-data-dev:/var/lib/postgresql/data
  test-db:
    image: postgres:15
    container_name: test-db
    environment:
      POSTGRES_USER: testuser
      POSTGRES_PASSWORD: testpass
      POSTGRES_DB: testdb
    ports:
      - "5435:5432"
    networks:
      - lsib-network
    volumes:
      - ./db-data-test:/var/lib/postgresql/data
networks:
  lsib-network: