services:
  dev-db:
    image: postgres:15
    container_name: dev-db
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5434:5432"
networks:
  lsib-network: